### PR TITLE
feat: Add listener for server sockets

### PR DESCRIPTION
**Pull request by reneca**
The new listener simplify the creation of server sockets. It have a _ListenerSettings_ to create whatever the connection:
- UNIX
- TCP
- SSL

### CODE REVIEW

**Comment by oschijns** [comment]
Could you check if it worth including QUIC in this PR?
https://quicwg.org/

**Comment by reneca** [comment]
> Could you check if it worth including QUIC in this PR? https://quicwg.org/

The goal is to avoid huge merge request. QUIC will be a great adding, but in a next PR.

**Review by oschijns — APPROVED** [review]

**Review by oschijns — APPROVED** [review]
Good with me

**Review by Timmy80 — APPROVED** [review]
Nice no issues found 👍

**Pull request merged**
